accessing
exceptionOop: anObject

   exceptionOop := anObject
